project:
  type: website

website:
  title: "SuzyZsj"
  favicon: "Images/paw.png"
  
  navbar:
    logo: "Images/bichon.png"
    search: true
    left:
    - text: "Hands-on Exercise"
      menu: 
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "Hands-on Exercise 3a"
          href: "Hands-on_Ex/Hands-on_Ex03a/Hands-on_Ex03a.html"
        - text: "Hands-on Exercise 3b"
          href: "Hands-on_Ex/Hands-on_Ex03b/Hands-on_Ex03b.html"          
    - text: "In-class Exercise"
      menu: 
        - text: "In-class Exercise 1"
          href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
    - text: "Take-home Exercise"
      menu: 
        - text: "Take-home Exercise 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
        - text: "Take-home Exercise 2"
          href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"          
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/shujie-zhang-202438267/
        aria-label: Linkedin
      - href: about.qmd
        text: About

      
format:
  html:
    theme: sketchy
    css: styles.css
    toc: true

editor: visual

