---
title: "Take-home Exercise 1"
author: "Suzy"
date: "January 16,2024"
execute: 
  eval: true
  echo: true
  warning: false
editor: visual
---

```{=html}
<style>
details.custom-block {
  border: 1px solid #aaa;
  border-radius: 4px;
  padding: 0.5em;
  background-color: #f9f9f9;
}

summary.custom-block-summary {
  font-weight: bold;
  color: #333;
}
</style>
```
# Project Brief

While Singapore has made strides in reducing disparities in family wealth, its education policy is committed to ensuring high-quality education in every school. However, the general public still perceives persistent educational inequalities, especially between elite and ordinary community schools, as well as among students from different socioeconomic backgrounds and immigrant families. We will delve deeply into the state of education in Singapore, based on the data provided by the 2022 Programme for International Student Assessment (PISA).

# Project Objectives

The aim of this project is to conduct an Exploratory Data Analysis (EDA) using the 2022 PISA data, focusing on students in Singapore. The analysis will explore the distribution of Singaporean students' performance in mathematics, reading, and science, and examine the relationship between these performances and various factors such as school type, gender, and socioeconomic status. The analysis will be visualized effectively to communicate the findings derived from the data.

# Data Preparation

## Install and launching R packages

We use the `pacman::p_load()` function to load the required R packages into our working environment. The loaded packages are:

-   **tidyverse**: A collection of packages for data manipulation and visualization, including ggplot2, dplyr, tidyr, etc.

-   **ggplot2**: For creating complex charts and visualizations.

-   **dplyr**: For data manipulation and cleaning.

-   **readr**: For reading CSV files.

-   **ggpubr**: Provides easy-to-use functions for creating publication-quality charts.

-   **scales**: For beautifying charts, like adjusting axes.

-   **lubridate**: For handling date data, if your data includes time information.

-   **forcats**: For handling categorical variables, which could be useful for dealing with variables like gender and school IDs.

-   **gridExtra** or **cowplot**: For arranging multiple plots on a single page.

-   **corrplot**: For visualizing correlations between variables.

-   **Hmisc**: Contains many functions useful for data analysis, such as descriptive statistics.

<details class="custom-block">
<summary class="custom-block-summary">Code Block</summary>

``` r
pacman::p_load(tidyverse, ggplot2, dplyr, readr, ggpubr,
scales,forcats, gridExtra, corrplot, Hmisc, lubridate)
```

## **Dataset Organization**

### **Data overview**

### **Research Variable Selection**

### **Data Structure**

### **Data Quality**

# Exploratory Data Analysis

## Distribution of performance in math, reading and science

## The relationship between gender and academic performance

## The relationship between school and academic performance

## The relationship between socioeconomic status and academic performance

## Comprehensive visualization
